# config file for dataservice

# 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
log_level: 1

grpc_server:
  address: "127.0.0.1:9301"  # required

grpc_log:
  level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  verbosity: 99

metrics_server:
  enabled: true
  address: "127.0.0.1:9301" # required when enabled is true
  url_path: "/metrics"

mysql:
  hosts: "192.168.220.130:3306"  # required
  users: "root"  # required
  password: "123456"  # required
  database: "data_workbench"  # required
  max_idle_conn: 16
  max_open_conn: 128
  conn_max_lifetime: 10m
  log_level: 4 # 1 => Silent, 2 => Error, 3 => Warn, 4 => Info
  slow_threshold: 2s

tracer:
  service_name: "dataservice"
  local_agent: "127.0.0.1:6851"
